[package]
name = "rocksql"
version = "0.1.0"
authors = ["Alex Angelini <alex.louis.angelini@gmail.com>"]

[dependencies]
bincode = "1.0.1"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"